[package]
name = "nes-emulator"
version = "0.1.0"
edition = "2018"
default-run = "nes-emulator"

[[bin]]
name = "nes-emulator"
path = "src/main.rs"

[dependencies]
cpu = { path = "../cpu" }
lazy_static = "1.4.0"
bitflags = "1.2.1"

sdl2 = "0.34.0"
rand = "=0.7.3"
